package org.khasanof.forkJoinFramework;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.TimeUnit;

/**
 * Author: Nurislom
 * <br/>
 * Date: 2/14/2023
 * <br/>
 * Time: 12:41 PM
 * <br/>
 * Package: org.khasanof.forkJoinFramework
 */
public class FolderProcessorTest {

    @Test
    void folderProcessorTest() {
        ForkJoinPool forkJoinPool = new ForkJoinPool();

        FolderProcessor system = new FolderProcessor("C:\\Intel", "log");
        FolderProcessor apps = new FolderProcessor("C:\\Program Files", "log");
        FolderProcessor documents = new FolderProcessor("C:\\Program Files (x86)", "log");

        //Execute the three tasks in the pool using the execute() method.
        forkJoinPool.execute(system);
        forkJoinPool.execute(apps);
        forkJoinPool.execute(documents);

        //Write to the console information about the status of the pool every second
        //until the three tasks have finished their execution.
        do {

            System.out.printf("******************************************\n");
            System.out.printf("Main: Parallelism: %d\n", forkJoinPool.getParallelism());
            System.out.printf("Main: Active Threads: %d\n",
                    forkJoinPool.getActiveThreadCount());
            System.out.printf("Main: Task Count: %d\n", forkJoinPool.getQueuedTaskCount());
            System.out.printf("Main: Steal Count: %d\n", forkJoinPool.getStealCount());
            System.out.printf("******************************************\n");
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        } while ((!system.isDone()) || (!apps.isDone()) || (!documents.isDone()));

        forkJoinPool.shutdown();

        //Write the number of results generated by each task to the console.
        List<String> results;
        results = system.join();
        System.out.printf("System: %d files found.\n", results.size());
        results = apps.join();
        System.out.printf("Apps: %d files found.\n", results.size());
        results = documents.join();
        System.out.printf("Documents: %d files found.\n", results.size());
    }
}
